# Pandas
deals with  two data types
- series
- dataframes

### series
is a one dimensional dataframe ```tabular representation```

### dataframe 
multidimensional data 

In [1]:
# creating a series
import pandas as pd

### import individual element
to imprort just the series function from pandas type
```python
from pandas import Series
```
makes it so that instead of running 
```python
s = pd.Series('list datatype')
```
we instead write 
```python
s = Series('list datatype')
```

In [3]:
l = (1.0, 3.2, 4.5, 6.7, 8.96, 10.99)
l

(1.0, 3.2, 4.5, 6.7, 8.96, 10.99)

In [4]:
# convert list to series
s = pd.Series(l)
s

0     1.00
1     3.20
2     4.50
3     6.70
4     8.96
5    10.99
dtype: float64

In [5]:
# number of indexes available
s.index

RangeIndex(start=0, stop=6, step=1)

In [6]:
# type of data in series
s.dtype

dtype('float64')

In [7]:
# the values in a series
s.values

array([ 1.  ,  3.2 ,  4.5 ,  6.7 ,  8.96, 10.99])

### generating a series from a random numpy array


In [10]:
import numpy as np
np_list = np.random.normal(size = 10)
np_list

array([-1.13310335, -1.58695934, -0.56351393,  0.26803991,  0.29618169,
       -0.77520109,  0.50460964,  0.10068199, -0.43815469,  1.57015458])

In [11]:
# series from numpy list
s_np = pd.Series(np_list)
s_np

0   -1.133103
1   -1.586959
2   -0.563514
3    0.268040
4    0.296182
5   -0.775201
6    0.504610
7    0.100682
8   -0.438155
9    1.570155
dtype: float64

In [12]:
# check indexes 
s_np.index

RangeIndex(start=0, stop=10, step=1)

In [13]:
# check values 
s_np.values

array([-1.13310335, -1.58695934, -0.56351393,  0.26803991,  0.29618169,
       -0.77520109,  0.50460964,  0.10068199, -0.43815469,  1.57015458])