# Pandas
deals with  two data types
- series
- dataframes

### series
is a one dimensional dataframe ```tabular representation```

### dataframe 
multidimensional data 

In [1]:
# creating a series
import pandas as pd

#### import individual element
to imprort just the series function from pandas type
```python
from pandas import Series
```
makes it so that instead of running 
```python
s = pd.Series('list datatype')
```
we instead write 
```python
s = Series('list datatype')
```

In [3]:
l = (1.0, 3.2, 4.5, 6.7, 8.96, 10.99)
l

(1.0, 3.2, 4.5, 6.7, 8.96, 10.99)

In [4]:
# convert list to series
s = pd.Series(l)
s

0     1.00
1     3.20
2     4.50
3     6.70
4     8.96
5    10.99
dtype: float64

In [5]:
# number of indexes available
s.index

RangeIndex(start=0, stop=6, step=1)

In [6]:
# type of data in series
s.dtype

dtype('float64')

In [7]:
# the values in a series
s.values

array([ 1.  ,  3.2 ,  4.5 ,  6.7 ,  8.96, 10.99])

#### generating a series from a random numpy array


In [10]:
import numpy as np
np_list = np.random.normal(size = 10)
np_list

array([-1.13310335, -1.58695934, -0.56351393,  0.26803991,  0.29618169,
       -0.77520109,  0.50460964,  0.10068199, -0.43815469,  1.57015458])

In [11]:
# series from numpy list
s_np = pd.Series(np_list)
s_np

0   -1.133103
1   -1.586959
2   -0.563514
3    0.268040
4    0.296182
5   -0.775201
6    0.504610
7    0.100682
8   -0.438155
9    1.570155
dtype: float64

In [12]:
# check indexes 
s_np.index

RangeIndex(start=0, stop=10, step=1)

In [13]:
# check values 
s_np.values

array([-1.13310335, -1.58695934, -0.56351393,  0.26803991,  0.29618169,
       -0.77520109,  0.50460964,  0.10068199, -0.43815469,  1.57015458])

In [15]:
# check data type
s_np.dtype

dtype('float64')

#### changing the index of the series to a custom name

In [19]:
s3 = pd.Series(list(l), index = ['Jan', 'Feb', 'Mar', 'May', 'Jun', 'Jul'])
s3

Jan     1.00
Feb     3.20
Mar     4.50
May     6.70
Jun     8.96
Jul    10.99
dtype: float64

In [20]:
# index names
s3.index

Index(['Jan', 'Feb', 'Mar', 'May', 'Jun', 'Jul'], dtype='object')

#### creating series from dictionary

In [21]:
capitals = {'Nairobi': 'Kenya', 
           'Accra': 'Ghana',
           'Khartoum': 'Sudan',
           'Addis Ababa': 'Ethiopia',
           'Dodoma': 'Tanzania',
           'Kigali': 'Rwanda',
           'Kampala': 'Uganda'}
capitals

{'Nairobi': 'Kenya',
 'Accra': 'Ghana',
 'Khartoum': 'Sudan',
 'Addis Ababa': 'Ethiopia',
 'Dodoma': 'Tanzania',
 'Kigali': 'Rwanda',
 'Kampala': 'Uganda'}

In [22]:
# creating series
cap_series = pd.Series(capitals)
cap_series

Nairobi           Kenya
Accra             Ghana
Khartoum          Sudan
Addis Ababa    Ethiopia
Dodoma         Tanzania
Kigali           Rwanda
Kampala          Uganda
dtype: object

#### idexing and slicing

In [23]:
# third series 
cap_series[2]

'Sudan'

In [24]:
# return the first three rows
cap_series[0:3]

Nairobi     Kenya
Accra       Ghana
Khartoum    Sudan
dtype: object

In [25]:
# using iloc to retrieve specific rows
# locate third to fifth row
cap_series.iloc[2:6]

Khartoum          Sudan
Addis Ababa    Ethiopia
Dodoma         Tanzania
Kigali           Rwanda
dtype: object

**notice** use of ```[]``` in using iloc

#### counting and selecting

In [27]:
# counting
cap_series.count()

7

In [28]:
# counting indexes
cap_series.size

7

**notice** if a value is replaced by NaN it stops being a value in a series

In [35]:
# selecting
cap_series['Nairobi'] = float('NaN')

In [36]:
cap_series

Nairobi             NaN
Accra             Ghana
Khartoum          Sudan
Addis Ababa    Ethiopia
Dodoma         Tanzania
Kigali           Rwanda
Kampala          Uganda
dtype: object

**Notice** 

count-- number of elements 

size -- number of positions

In [37]:
cap_series.count()

6

In [39]:
cap_series.size

7

### Dataframes

In [41]:
cars = {'make':['Toyota', 'Ford', 'Subaru', 'Nissan', 'BMW'],
       'model':['Corola', 'Focus', 'Forester', 'Note', '520i'],
       'msrp':[2_000_000, 1_876_000, 3_245_678, 800_000, 2_250_630]}
cars

{'make': ['Toyota', 'Ford', 'Subaru', 'Nissan', 'BMW'],
 'model': ['Corola', 'Focus', 'Forester', 'Note', '520i'],
 'msrp': [2000000, 1876000, 3245678, 800000, 2250630]}

In [42]:
carData = pd.DataFrame(cars)
carData

make     model     msrp
0  Toyota    Corola  2000000
1    Ford     Focus  1876000
2  Subaru  Forester  3245678
3  Nissan      Note   800000
4     BMW      520i  2250630

In [44]:
# column data types
carData.dtypes

make     object
model    object
msrp      int64
dtype: object

In [46]:
# column titles
carData.columns

Index(['make', 'model', 'msrp'], dtype='object')

In [48]:
# number of elements
carData.size

15

In [50]:
# select a column
carData['make']

0    Toyota
1      Ford
2    Subaru
3    Nissan
4       BMW
Name: make, dtype: object

In [53]:
carData.

NameError: name 'o' is not defined