# Pandas
deals with  two data types
- series
- dataframes

### series
is a one dimensional dataframe ```tabular representation```

### dataframe 
multidimensional data 

In [1]:
# creating a series
import pandas as pd

#### import individual element
to imprort just the series function from pandas type
```python
from pandas import Series
```
makes it so that instead of running 
```python
s = pd.Series('list datatype')
```
we instead write 
```python
s = Series('list datatype')
```

In [3]:
l = (1.0, 3.2, 4.5, 6.7, 8.96, 10.99)
l

(1.0, 3.2, 4.5, 6.7, 8.96, 10.99)

In [4]:
# convert list to series
s = pd.Series(l)
s

0     1.00
1     3.20
2     4.50
3     6.70
4     8.96
5    10.99
dtype: float64

In [5]:
# number of indexes available
s.index

RangeIndex(start=0, stop=6, step=1)

In [6]:
# type of data in series
s.dtype

dtype('float64')

In [7]:
# the values in a series
s.values

array([ 1.  ,  3.2 ,  4.5 ,  6.7 ,  8.96, 10.99])

#### generating a series from a random numpy array


In [10]:
import numpy as np
np_list = np.random.normal(size = 10)
np_list

array([-1.13310335, -1.58695934, -0.56351393,  0.26803991,  0.29618169,
       -0.77520109,  0.50460964,  0.10068199, -0.43815469,  1.57015458])

In [11]:
# series from numpy list
s_np = pd.Series(np_list)
s_np

0   -1.133103
1   -1.586959
2   -0.563514
3    0.268040
4    0.296182
5   -0.775201
6    0.504610
7    0.100682
8   -0.438155
9    1.570155
dtype: float64

In [12]:
# check indexes 
s_np.index

RangeIndex(start=0, stop=10, step=1)

In [13]:
# check values 
s_np.values

array([-1.13310335, -1.58695934, -0.56351393,  0.26803991,  0.29618169,
       -0.77520109,  0.50460964,  0.10068199, -0.43815469,  1.57015458])

In [15]:
# check data type
s_np.dtype

dtype('float64')

#### changing the index of the series to a custom name

In [19]:
s3 = pd.Series(list(l), index = ['Jan', 'Feb', 'Mar', 'May', 'Jun', 'Jul'])
s3

Jan     1.00
Feb     3.20
Mar     4.50
May     6.70
Jun     8.96
Jul    10.99
dtype: float64

In [20]:
# index names
s3.index

Index(['Jan', 'Feb', 'Mar', 'May', 'Jun', 'Jul'], dtype='object')

#### creating series from dictionary

In [21]:
capitals = {'Nairobi': 'Kenya', 
           'Accra': 'Ghana',
           'Khartoum': 'Sudan',
           'Addis Ababa': 'Ethiopia',
           'Dodoma': 'Tanzania',
           'Kigali': 'Rwanda',
           'Kampala': 'Uganda'}
capitals

{'Nairobi': 'Kenya',
 'Accra': 'Ghana',
 'Khartoum': 'Sudan',
 'Addis Ababa': 'Ethiopia',
 'Dodoma': 'Tanzania',
 'Kigali': 'Rwanda',
 'Kampala': 'Uganda'}

In [22]:
# creating series
cap_series = pd.Series(capitals)
cap_series

Nairobi           Kenya
Accra             Ghana
Khartoum          Sudan
Addis Ababa    Ethiopia
Dodoma         Tanzania
Kigali           Rwanda
Kampala          Uganda
dtype: object

#### idexing and slicing

In [23]:
# third series 
cap_series[2]

'Sudan'

In [24]:
# return the first three rows
cap_series[0:3]

Nairobi     Kenya
Accra       Ghana
Khartoum    Sudan
dtype: object

In [25]:
# using iloc to retrieve specific rows
# locate third to fifth row
cap_series.iloc[2:6]

Khartoum          Sudan
Addis Ababa    Ethiopia
Dodoma         Tanzania
Kigali           Rwanda
dtype: object

**notice** use of ```[]``` in using iloc

#### counting and selecting

In [27]:
# counting
cap_series.count()

7

In [28]:
# counting indexes
cap_series.size

7

**notice** if a value is replaced by NaN it stops being a value in a series

In [35]:
# selecting
cap_series['Nairobi'] = float('NaN')

In [36]:
cap_series

Nairobi             NaN
Accra             Ghana
Khartoum          Sudan
Addis Ababa    Ethiopia
Dodoma         Tanzania
Kigali           Rwanda
Kampala          Uganda
dtype: object

**Notice** 

count-- number of elements 

size -- number of positions

In [37]:
cap_series.count()

6

In [39]:
cap_series.size

7

### Dataframes

In [41]:
cars = {'make':['Toyota', 'Ford', 'Subaru', 'Nissan', 'BMW'],
       'model':['Corola', 'Focus', 'Forester', 'Note', '520i'],
       'msrp':[2_000_000, 1_876_000, 3_245_678, 800_000, 2_250_630]}
cars

{'make': ['Toyota', 'Ford', 'Subaru', 'Nissan', 'BMW'],
 'model': ['Corola', 'Focus', 'Forester', 'Note', '520i'],
 'msrp': [2000000, 1876000, 3245678, 800000, 2250630]}

In [42]:
carData = pd.DataFrame(cars)
carData

make     model     msrp
0  Toyota    Corola  2000000
1    Ford     Focus  1876000
2  Subaru  Forester  3245678
3  Nissan      Note   800000
4     BMW      520i  2250630

In [44]:
# column data types
carData.dtypes

make     object
model    object
msrp      int64
dtype: object

In [46]:
# column titles
carData.columns

Index(['make', 'model', 'msrp'], dtype='object')

In [48]:
# number of elements
carData.size

15

In [50]:
# select a column
carData['make']

0    Toyota
1      Ford
2    Subaru
3    Nissan
4       BMW
Name: make, dtype: object

In [56]:
# change the row indexes to more natural counting
carData.index = [1, 2, 3, 4, 5]
carData

make     model     msrp
1  Toyota    Corola  2000000
2    Ford     Focus  1876000
3  Subaru  Forester  3245678
4  Nissan      Note   800000
5     BMW      520i  2250630

In [57]:
# add a new columns
carData['Year'] = [2019, 2016, 2015, 2020, 2017]

In [58]:
carData

make     model     msrp  Year
1  Toyota    Corola  2000000  2019
2    Ford     Focus  1876000  2016
3  Subaru  Forester  3245678  2015
4  Nissan      Note   800000  2020
5     BMW      520i  2250630  2017

#### creating random values

In [59]:
# create a random 5 * 3 numpy array
rand = np.random.randn(5, 3)
rand

array([[-0.45741316,  0.35859425, -1.11369455],
       [ 0.20279183,  0.00592733, -0.12741281],
       [ 0.49664794, -0.02788434, -0.14991844],
       [ 1.07127355, -1.00953751, -1.01426257],
       [ 1.35799534,  1.15650423, -1.7440679 ]])

In [60]:
# creat column names 
colname = ['X1', 'X2', 'X3']

In [62]:
# creating dataframe
rand_df = pd.DataFrame(rand, columns = colname)
rand_df

X1        X2        X3
0 -0.457413  0.358594 -1.113695
1  0.202792  0.005927 -0.127413
2  0.496648 -0.027884 -0.149918
3  1.071274 -1.009538 -1.014263
4  1.357995  1.156504 -1.744068

In [64]:
# sum of a column
rand_df['X3'].sum()

-4.149356264395075

In [65]:
# describe the data
rand_df.describe()

X1        X2        X3
count  5.000000  5.000000  5.000000
mean   0.534259  0.096721 -0.829871
std    0.717918  0.780912  0.690307
min   -0.457413 -1.009538 -1.744068
25%    0.202792 -0.027884 -1.113695
50%    0.496648  0.005927 -1.014263
75%    1.071274  0.358594 -0.149918
max    1.357995  1.156504 -0.127413

## Reading Data

In [67]:
# using readcsv
path = 'titanic_train.csv'
train = pd.read_csv(path)
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
# analysis on age 
age = train['age']

In [ ]:
age