# Using Numpy 
```python
import numpy as np
import sys
```

## basic info
### What is numpy
A multi-dimensional array data type
### Why numpy over lists
| Numpy array |list|
|-------------|-----|
|Fast - uses fixed types|Slow - uses object types|
**Because numpy requires:**
1. less memory to store values 

2. Doesn't require type checking of elements stored

|Numpy array |list|
|------------|-----|
|uses contiguous memory| uses pointers to information in memory stak|

- all elements in a numpy array are next to each other

Makes use of ``**SIMD(single instrucction multiple data)**``
- allows more efficient processing by the cpu. 
- allows for multiple data arithmetic

Makes better use of the ```cache```
- makes itteration easier
- lowers load on memory lookup

|Numpy array |list|
|------------|-----|
|value arithmetic| doesn't allow value arithmetic|

## Application of Numpy
- MATLAB replacement
- Ploting(matplotlib)
- Backend ```storing data``` (Pandas, connect 4, Digital photography)
- allows for machine learning



In [1]:
# add numpy into the project
# if it doesnt work use pip install on conda base
import numpy as np

### basics

In [3]:
# one dim array 
a = np.array([1,2, 3])
print(a)

[1 2 3]


In [4]:
# multidimensional array
b = np.array([[1, 2, 3, 4],[ 5, 6, 7, 8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
# dimensions of a numpy array
# size of a
a.ndim

1

In [6]:
# dims of b
b.ndim

2

In [7]:
# shapes of arrays
# returns (row, col)
# shape a
a.shape

(3,)

In [8]:
# b shape
b.shape

(2, 4)

In [9]:
# data type in the array
# data in a
a.dtype

dtype('int32')

In [10]:
# space each value occupies
# space in a
a.itemsize

4

In [12]:
# total space occipied
# a total space
a.itemsize * a.size

12

#### Tip
To change how data is stored in a numpy array create array as follows
```python
a = np.array([1, 2, 3], dtype = 'int16')
# stores data as int16 instead of the default int32
```

to get the number of elements in an array 
```python
a.size 
# returns 3
```

Instead of running ```a.itemsize * a.size``` to get total memory space.

run 
```python
a.nbytes
# returns 12
```

**Notice:** ```floats``` occupy more memory space than ```ints``` by default

### Accessing and Manupulating elements 