## Introduction to Numpy and Pandas

### Numpy
Also ```Numerical Python```.

Is a library for developing matrixes and multidimensional arrays 

```python3
import numpy as np
```
```np``` - is a an **alias** for numpy as used within a file.

In [2]:
# including numpy in the project
import numpy as np 

In [3]:
# creating a one dim array
# starting with a list
l = [1, 2, 3, 4, 5]

# confirm the type 
type(l)

list

In [5]:
# creating a one dim
oneDim = np.array(l)

# confirm type
type(oneDim)

numpy.ndarray

In [6]:
# count number of rows 
oneDim.ndim

1

In [7]:
# counting number of columns
oneDim.shape 

(5,)

In [14]:
# check the data type 
oneDim.dtype

dtype('int32')

In [15]:
# transposition
print(oneDim)
t = oneDim.T
t

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

## Python Data Type
### integers
```python
x = 9
print(type(x))
```
**output**
```
>> int
```
### floats
```python
x = 9.0
print(type(x))
```
**output**
```
>> float
```
### Booleans
```python
x = True
print(type(x))
```
**output**
```
>> Bool
```
### String
```python
x = 'hello'
print(type(x))
```
**output**
```
>> str
```
### list
```python
x = [9.0, 1, 2, 4]
print(type(x))
```
**output**
```
>> list
```
### tuple
```python
x = (9.0, 1, 2, 4)
print(type(x))
```
**output**
```
>> tuple
```

### np.array().T
- transposes arrays of greater than two dimensions 

In [19]:
# creating an array with 3 rows and 4 columns 
# using arange(start, stop, step) to create a random number array
samp = np.arange(12)

In [20]:
samp

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
# rearange the array to be 3 * 4
re_samp = samp.reshape(3, 4)
re_samp

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
# create values equaly spaced between two numbers
# using np.linspace(start, stop, number of numbers)
# uses an arithmetic progression
equal = np.linspace(0, 1, 10)
equal

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [24]:
# dividing a region with such that first number is log10(start) last number is log10(end)
# notice all numbers are equally spaced logs
logs = np.logspace(1, 3, 8)
logs

array([  10.        ,   19.30697729,   37.2759372 ,   71.9685673 ,
        138.94954944,  268.26957953,  517.94746792, 1000.        ])

In [27]:
# generating a random n-dim array of just zeros
# notice that it accepts a tuple as input
nil = np.zeros((2, 4))
nil

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# one vector of length 6
one = np.ones(6)
one
# one matrix of ones (4*4)
